//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Infrastructure.Resources.Messages.en", typeof(Messages_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked. Please contact the administrator..
        /// </summary>
        internal static string Auth_Account_Locked {
            get {
                return ResourceManager.GetString("Auth.Account.Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        internal static string Auth_Login_Failed {
            get {
                return ResourceManager.GetString("Auth.Login.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in successfully..
        /// </summary>
        internal static string Auth_Login_Success {
            get {
                return ResourceManager.GetString("Auth.Login.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged out successfully..
        /// </summary>
        internal static string Auth_Logout_Success {
            get {
                return ResourceManager.GetString("Auth.Logout.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully..
        /// </summary>
        internal static string Auth_Password_Changed {
            get {
                return ResourceManager.GetString("Auth.Password.Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation does not match..
        /// </summary>
        internal static string Auth_Password_Mismatch {
            get {
                return ResourceManager.GetString("Auth.Password.Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset successfully..
        /// </summary>
        internal static string Auth_Password_Reseted {
            get {
                return ResourceManager.GetString("Auth.Password.Reseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. Please log in again..
        /// </summary>
        internal static string Auth_Session_Expired {
            get {
                return ResourceManager.GetString("Auth.Session.Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired token..
        /// </summary>
        internal static string Auth_Token_Invalid {
            get {
                return ResourceManager.GetString("Auth.Token.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create record..
        /// </summary>
        internal static string Common_Create_Failed {
            get {
                return ResourceManager.GetString("Common.Create.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record created successfully..
        /// </summary>
        internal static string Common_Create_Success {
            get {
                return ResourceManager.GetString("Common.Create.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete record..
        /// </summary>
        internal static string Common_Delete_Failed {
            get {
                return ResourceManager.GetString("Common.Delete.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted successfully..
        /// </summary>
        internal static string Common_Delete_Success {
            get {
                return ResourceManager.GetString("Common.Delete.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed..
        /// </summary>
        internal static string Common_Failed {
            get {
                return ResourceManager.GetString("Common.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save record..
        /// </summary>
        internal static string Common_Save_Failed {
            get {
                return ResourceManager.GetString("Common.Save.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record saved successfully..
        /// </summary>
        internal static string Common_Save_Success {
            get {
                return ResourceManager.GetString("Common.Save.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully..
        /// </summary>
        internal static string Common_Success {
            get {
                return ResourceManager.GetString("Common.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update record..
        /// </summary>
        internal static string Common_Update_Failed {
            get {
                return ResourceManager.GetString("Common.Update.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record updated successfully..
        /// </summary>
        internal static string Common_Update_Success {
            get {
                return ResourceManager.GetString("Common.Update.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request. Please check your input..
        /// </summary>
        internal static string Error_BadRequest {
            get {
                return ResourceManager.GetString("Error.BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be deleted in its current state..
        /// </summary>
        internal static string Error_CannotDelete {
            get {
                return ResourceManager.GetString("Error.CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already in use or has a conflict..
        /// </summary>
        internal static string Error_Conflict {
            get {
                return ResourceManager.GetString("Error.Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to perform this action..
        /// </summary>
        internal static string Error_Forbidden {
            get {
                return ResourceManager.GetString("Error.Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please try again later..
        /// </summary>
        internal static string Error_InternalServer {
            get {
                return ResourceManager.GetString("Error.InternalServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be deleted because it is being used by other records..
        /// </summary>
        internal static string Error_InUse {
            get {
                return ResourceManager.GetString("Error.InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found..
        /// </summary>
        internal static string Error_NotFound {
            get {
                return ResourceManager.GetString("Error.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is temporarily unavailable. Please try again later..
        /// </summary>
        internal static string Error_ServiceUnavailable {
            get {
                return ResourceManager.GetString("Error.ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request timed out. Please try again..
        /// </summary>
        internal static string Error_Timeout {
            get {
                return ResourceManager.GetString("Error.Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized. Please log in again..
        /// </summary>
        internal static string Error_Unauthorized {
            get {
                return ResourceManager.GetString("Error.Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export failed. Please try again..
        /// </summary>
        internal static string Export_Failed {
            get {
                return ResourceManager.GetString("Export.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available to export..
        /// </summary>
        internal static string Export_NoData {
            get {
                return ResourceManager.GetString("Export.NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data exported successfully..
        /// </summary>
        internal static string Export_Success {
            get {
                return ResourceManager.GetString("Export.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed. Please check the file and try again..
        /// </summary>
        internal static string Import_Failed {
            get {
                return ResourceManager.GetString("Import.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size exceeds the allowed limit of {0} MB..
        /// </summary>
        internal static string Import_FileTooLarge {
            get {
                return ResourceManager.GetString("Import.FileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format. Please use the provided template..
        /// </summary>
        internal static string Import_InvalidFileFormat {
            get {
                return ResourceManager.GetString("Import.InvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported {0} records. {1} records failed..
        /// </summary>
        internal static string Import_Partial {
            get {
                return ResourceManager.GetString("Import.Partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported {0} records successfully..
        /// </summary>
        internal static string Import_Success {
            get {
                return ResourceManager.GetString("Import.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This menu path is already in use..
        /// </summary>
        internal static string Menu_PathExisted {
            get {
                return ResourceManager.GetString("Menu.PathExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Role is already in use..
        /// </summary>
        internal static string Role_Existed {
            get {
                return ResourceManager.GetString("Role.Existed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to modify this role..
        /// </summary>
        internal static string Role_NotAllowEdit {
            get {
                return ResourceManager.GetString("Role.NotAllowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not found..
        /// </summary>
        internal static string Role_NotFound {
            get {
                return ResourceManager.GetString("Role.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The protected role cannot be modified..
        /// </summary>
        internal static string Role_Protected {
            get {
                return ResourceManager.GetString("Role.Protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Status_Active {
            get {
                return ResourceManager.GetString("Status.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string Status_Approved {
            get {
                return ResourceManager.GetString("Status.Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Status_Cancelled {
            get {
                return ResourceManager.GetString("Status.Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string Status_Closed {
            get {
                return ResourceManager.GetString("Status.Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Status_Completed {
            get {
                return ResourceManager.GetString("Status.Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        internal static string Status_Draft {
            get {
                return ResourceManager.GetString("Status.Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string Status_Inactive {
            get {
                return ResourceManager.GetString("Status.Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string Status_InProgress {
            get {
                return ResourceManager.GetString("Status.InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string Status_Locked {
            get {
                return ResourceManager.GetString("Status.Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Approval.
        /// </summary>
        internal static string Status_Pending {
            get {
                return ResourceManager.GetString("Status.Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string Status_Rejected {
            get {
                return ResourceManager.GetString("Status.Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload failed. Please try again..
        /// </summary>
        internal static string Upload_Failed {
            get {
                return ResourceManager.GetString("Upload.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type is not allowed. Accepted types: {0}..
        /// </summary>
        internal static string Upload_InvalidType {
            get {
                return ResourceManager.GetString("Upload.InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file was uploaded..
        /// </summary>
        internal static string Upload_NoFileUploaded {
            get {
                return ResourceManager.GetString("Upload.NoFileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully..
        /// </summary>
        internal static string Upload_Success {
            get {
                return ResourceManager.GetString("Upload.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size exceeds the allowed limit of {0} MB..
        /// </summary>
        internal static string Upload_TooLarge {
            get {
                return ResourceManager.GetString("Upload.TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Your Email Address Change.
        /// </summary>
        internal static string User_ChangeEmailSubject {
            get {
                return ResourceManager.GetString("User.ChangeEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: Your Account Email Has Been Changed.
        /// </summary>
        internal static string User_EmailChangedNotiSubject {
            get {
                return ResourceManager.GetString("User.EmailChangedNotiSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already in use..
        /// </summary>
        internal static string User_EmailExisted {
            get {
                return ResourceManager.GetString("User.EmailExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username is already in use..
        /// </summary>
        internal static string User_Existed {
            get {
                return ResourceManager.GetString("User.Existed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to modify this user..
        /// </summary>
        internal static string User_NotAllowEdit {
            get {
                return ResourceManager.GetString("User.NotAllowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user not found..
        /// </summary>
        internal static string User_NotFound {
            get {
                return ResourceManager.GetString("User.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phone number is already in use..
        /// </summary>
        internal static string User_PhoneExisted {
            get {
                return ResourceManager.GetString("User.PhoneExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code is already in use..
        /// </summary>
        internal static string Validation_CodeExisted {
            get {
                return ResourceManager.GetString("Validation.CodeExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}..
        /// </summary>
        internal static string Validation_DateRange {
            get {
                return ResourceManager.GetString("Validation.DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists in the system..
        /// </summary>
        internal static string Validation_Duplicate {
            get {
                return ResourceManager.GetString("Validation.Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password..
        /// </summary>
        internal static string Validation_IncorrectPassword {
            get {
                return ResourceManager.GetString("Validation.IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid date..
        /// </summary>
        internal static string Validation_InvalidDate {
            get {
                return ResourceManager.GetString("Validation.InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid email address..
        /// </summary>
        internal static string Validation_InvalidEmail {
            get {
                return ResourceManager.GetString("Validation.InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has an invalid format..
        /// </summary>
        internal static string Validation_InvalidFormat {
            get {
                return ResourceManager.GetString("Validation.InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid phone number..
        /// </summary>
        internal static string Validation_InvalidPhone {
            get {
                return ResourceManager.GetString("Validation.InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} references a record that does not exist..
        /// </summary>
        internal static string Validation_InvalidReference {
            get {
                return ResourceManager.GetString("Validation.InvalidReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than or equal to {1}..
        /// </summary>
        internal static string Validation_Max {
            get {
                return ResourceManager.GetString("Validation.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not exceed {1} characters..
        /// </summary>
        internal static string Validation_MaxLength {
            get {
                return ResourceManager.GetString("Validation.MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1}..
        /// </summary>
        internal static string Validation_Min {
            get {
                return ResourceManager.GetString("Validation.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be at least {1} characters..
        /// </summary>
        internal static string Validation_MinLength {
            get {
                return ResourceManager.GetString("Validation.MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a whole number..
        /// </summary>
        internal static string Validation_MustBeInteger {
            get {
                return ResourceManager.GetString("Validation.MustBeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a positive number..
        /// </summary>
        internal static string Validation_MustBePositive {
            get {
                return ResourceManager.GetString("Validation.MustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}..
        /// </summary>
        internal static string Validation_Range {
            get {
                return ResourceManager.GetString("Validation.Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2} characters..
        /// </summary>
        internal static string Validation_RangeLength {
            get {
                return ResourceManager.GetString("Validation.RangeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        internal static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date must be before end date..
        /// </summary>
        internal static string Validation_StartDateGreaterThanEndDate {
            get {
                return ResourceManager.GetString("Validation.StartDateGreaterThanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is invalid or has expired..
        /// </summary>
        internal static string Validation_TokkenInValid {
            get {
                return ResourceManager.GetString("Validation.TokkenInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} approved successfully..
        /// </summary>
        internal static string Workflow_Approve_Success {
            get {
                return ResourceManager.GetString("Workflow.Approve.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cancelled successfully..
        /// </summary>
        internal static string Workflow_Cancel_Success {
            get {
                return ResourceManager.GetString("Workflow.Cancel.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} closed successfully..
        /// </summary>
        internal static string Workflow_Close_Success {
            get {
                return ResourceManager.GetString("Workflow.Close.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change status from {0} to {1}..
        /// </summary>
        internal static string Workflow_InvalidTransition {
            get {
                return ResourceManager.GetString("Workflow.InvalidTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rejected successfully..
        /// </summary>
        internal static string Workflow_Reject_Success {
            get {
                return ResourceManager.GetString("Workflow.Reject.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reopened successfully..
        /// </summary>
        internal static string Workflow_Reopen_Success {
            get {
                return ResourceManager.GetString("Workflow.Reopen.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} submitted for approval successfully..
        /// </summary>
        internal static string Workflow_Submit_Success {
            get {
                return ResourceManager.GetString("Workflow.Submit.Success", resourceCulture);
            }
        }
    }
}
