//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_vi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_vi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Infrastructure.Resources.Messages.vi", typeof(Messages_vi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn đã bị khóa. Vui lòng liên hệ quản trị viên..
        /// </summary>
        internal static string Auth_Account_Locked {
            get {
                return ResourceManager.GetString("Auth.Account.Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không đúng..
        /// </summary>
        internal static string Auth_Login_Failed {
            get {
                return ResourceManager.GetString("Auth.Login.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công..
        /// </summary>
        internal static string Auth_Login_Success {
            get {
                return ResourceManager.GetString("Auth.Login.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất thành công..
        /// </summary>
        internal static string Auth_Logout_Success {
            get {
                return ResourceManager.GetString("Auth.Logout.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công..
        /// </summary>
        internal static string Auth_Password_Changed {
            get {
                return ResourceManager.GetString("Auth.Password.Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu không khớp..
        /// </summary>
        internal static string Auth_Password_Mismatch {
            get {
                return ResourceManager.GetString("Auth.Password.Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã được khôi phục thành công..
        /// </summary>
        internal static string Auth_Password_Reseted {
            get {
                return ResourceManager.GetString("Auth.Password.Reseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại..
        /// </summary>
        internal static string Auth_Session_Expired {
            get {
                return ResourceManager.GetString("Auth.Session.Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token không hợp lệ hoặc đã hết hạn..
        /// </summary>
        internal static string Auth_Token_Invalid {
            get {
                return ResourceManager.GetString("Auth.Token.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới bản ghi thất bại..
        /// </summary>
        internal static string Common_Create_Failed {
            get {
                return ResourceManager.GetString("Common.Create.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới bản ghi thành công..
        /// </summary>
        internal static string Common_Create_Success {
            get {
                return ResourceManager.GetString("Common.Create.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa bản ghi thất bại..
        /// </summary>
        internal static string Common_Delete_Failed {
            get {
                return ResourceManager.GetString("Common.Delete.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa bản ghi thành công..
        /// </summary>
        internal static string Common_Delete_Success {
            get {
                return ResourceManager.GetString("Common.Delete.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác thất bại..
        /// </summary>
        internal static string Common_Failed {
            get {
                return ResourceManager.GetString("Common.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu bản ghi thất bại..
        /// </summary>
        internal static string Common_Save_Failed {
            get {
                return ResourceManager.GetString("Common.Save.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu bản ghi thành công..
        /// </summary>
        internal static string Common_Save_Success {
            get {
                return ResourceManager.GetString("Common.Save.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác thành công..
        /// </summary>
        internal static string Common_Success {
            get {
                return ResourceManager.GetString("Common.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật bản ghi thất bại..
        /// </summary>
        internal static string Common_Update_Failed {
            get {
                return ResourceManager.GetString("Common.Update.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật bản ghi thành công..
        /// </summary>
        internal static string Common_Update_Success {
            get {
                return ResourceManager.GetString("Common.Update.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu không hợp lệ. Vui lòng kiểm tra lại thông tin..
        /// </summary>
        internal static string Error_BadRequest {
            get {
                return ResourceManager.GetString("Error.BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không thể xóa ở trạng thái hiện tại..
        /// </summary>
        internal static string Error_CannotDelete {
            get {
                return ResourceManager.GetString("Error.CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đang được sử dụng hoặc có xung đột dữ liệu..
        /// </summary>
        internal static string Error_Conflict {
            get {
                return ResourceManager.GetString("Error.Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền thực hiện thao tác này..
        /// </summary>
        internal static string Error_Forbidden {
            get {
                return ResourceManager.GetString("Error.Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi không mong muốn. Vui lòng thử lại sau..
        /// </summary>
        internal static string Error_InternalServer {
            get {
                return ResourceManager.GetString("Error.InternalServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không thể xóa vì đang được sử dụng bởi bản ghi khác..
        /// </summary>
        internal static string Error_InUse {
            get {
                return ResourceManager.GetString("Error.InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy {0}..
        /// </summary>
        internal static string Error_NotFound {
            get {
                return ResourceManager.GetString("Error.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ tạm thời không khả dụng. Vui lòng thử lại sau..
        /// </summary>
        internal static string Error_ServiceUnavailable {
            get {
                return ResourceManager.GetString("Error.ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu đã hết thời gian chờ. Vui lòng thử lại..
        /// </summary>
        internal static string Error_Timeout {
            get {
                return ResourceManager.GetString("Error.Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa đăng nhập. Vui lòng đăng nhập lại..
        /// </summary>
        internal static string Error_Unauthorized {
            get {
                return ResourceManager.GetString("Error.Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất dữ liệu thất bại. Vui lòng thử lại..
        /// </summary>
        internal static string Export_Failed {
            get {
                return ResourceManager.GetString("Export.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu để xuất..
        /// </summary>
        internal static string Export_NoData {
            get {
                return ResourceManager.GetString("Export.NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất dữ liệu thành công..
        /// </summary>
        internal static string Export_Success {
            get {
                return ResourceManager.GetString("Export.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập dữ liệu thất bại. Vui lòng kiểm tra lại file và thử lại..
        /// </summary>
        internal static string Import_Failed {
            get {
                return ResourceManager.GetString("Import.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước file vượt quá giới hạn cho phép {0} MB..
        /// </summary>
        internal static string Import_FileTooLarge {
            get {
                return ResourceManager.GetString("Import.FileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng file không hợp lệ. Vui lòng sử dụng file mẫu được cung cấp..
        /// </summary>
        internal static string Import_InvalidFileFormat {
            get {
                return ResourceManager.GetString("Import.InvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập thành công {0} bản ghi. {1} bản ghi thất bại..
        /// </summary>
        internal static string Import_Partial {
            get {
                return ResourceManager.GetString("Import.Partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập dữ liệu thành công {0} bản ghi..
        /// </summary>
        internal static string Import_Success {
            get {
                return ResourceManager.GetString("Import.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn này đã được sử dụng bởi một menu khác..
        /// </summary>
        internal static string Menu_PathExisted {
            get {
                return ResourceManager.GetString("Menu.PathExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vai trò này đã được sử dụng..
        /// </summary>
        internal static string Role_Existed {
            get {
                return ResourceManager.GetString("Role.Existed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền chỉnh sửa vai trò này..
        /// </summary>
        internal static string Role_NotAllowEdit {
            get {
                return ResourceManager.GetString("Role.NotAllowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy vai trò..
        /// </summary>
        internal static string Role_NotFound {
            get {
                return ResourceManager.GetString("Role.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể chỉnh sửa vai trò được bảo vệ..
        /// </summary>
        internal static string Role_Protected {
            get {
                return ResourceManager.GetString("Role.Protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang hoạt động.
        /// </summary>
        internal static string Status_Active {
            get {
                return ResourceManager.GetString("Status.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã phê duyệt.
        /// </summary>
        internal static string Status_Approved {
            get {
                return ResourceManager.GetString("Status.Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hủy.
        /// </summary>
        internal static string Status_Cancelled {
            get {
                return ResourceManager.GetString("Status.Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã đóng.
        /// </summary>
        internal static string Status_Closed {
            get {
                return ResourceManager.GetString("Status.Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        internal static string Status_Completed {
            get {
                return ResourceManager.GetString("Status.Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nháp.
        /// </summary>
        internal static string Status_Draft {
            get {
                return ResourceManager.GetString("Status.Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hoạt động.
        /// </summary>
        internal static string Status_Inactive {
            get {
                return ResourceManager.GetString("Status.Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý.
        /// </summary>
        internal static string Status_InProgress {
            get {
                return ResourceManager.GetString("Status.InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã khóa.
        /// </summary>
        internal static string Status_Locked {
            get {
                return ResourceManager.GetString("Status.Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ phê duyệt.
        /// </summary>
        internal static string Status_Pending {
            get {
                return ResourceManager.GetString("Status.Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã từ chối.
        /// </summary>
        internal static string Status_Rejected {
            get {
                return ResourceManager.GetString("Status.Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải lên file thất bại. Vui lòng thử lại..
        /// </summary>
        internal static string Upload_Failed {
            get {
                return ResourceManager.GetString("Upload.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại file không được phép. Các loại được chấp nhận: {0}..
        /// </summary>
        internal static string Upload_InvalidType {
            get {
                return ResourceManager.GetString("Upload.InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có tệp nào được tải lên..
        /// </summary>
        internal static string Upload_NoFileUploaded {
            get {
                return ResourceManager.GetString("Upload.NoFileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải lên file thành công..
        /// </summary>
        internal static string Upload_Success {
            get {
                return ResourceManager.GetString("Upload.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước file vượt quá giới hạn cho phép {0} MB..
        /// </summary>
        internal static string Upload_TooLarge {
            get {
                return ResourceManager.GetString("Upload.TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận thay đổi địa chỉ email.
        /// </summary>
        internal static string User_ChangeEmailSubject {
            get {
                return ResourceManager.GetString("User.ChangeEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo: Địa chỉ email của tài khoản đã được thay đổi.
        /// </summary>
        internal static string User_EmailChangedNotiSubject {
            get {
                return ResourceManager.GetString("User.EmailChangedNotiSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email này đã được sử dụng..
        /// </summary>
        internal static string User_EmailExisted {
            get {
                return ResourceManager.GetString("User.EmailExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản này đã được sử dụng..
        /// </summary>
        internal static string User_Existed {
            get {
                return ResourceManager.GetString("User.Existed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền chỉnh sửa người dùng này..
        /// </summary>
        internal static string User_NotAllowEdit {
            get {
                return ResourceManager.GetString("User.NotAllowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy người dùng này..
        /// </summary>
        internal static string User_NotFound {
            get {
                return ResourceManager.GetString("User.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại này đã được sử dụng..
        /// </summary>
        internal static string User_PhoneExisted {
            get {
                return ResourceManager.GetString("User.PhoneExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã này đã được sử dụng..
        /// </summary>
        internal static string Validation_CodeExisted {
            get {
                return ResourceManager.GetString("Validation.CodeExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải nằm trong khoảng từ {1} đến {2}..
        /// </summary>
        internal static string Validation_DateRange {
            get {
                return ResourceManager.GetString("Validation.DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã tồn tại trong hệ thống..
        /// </summary>
        internal static string Validation_Duplicate {
            get {
                return ResourceManager.GetString("Validation.Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không chính xác..
        /// </summary>
        internal static string Validation_IncorrectPassword {
            get {
                return ResourceManager.GetString("Validation.IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không phải ngày hợp lệ..
        /// </summary>
        internal static string Validation_InvalidDate {
            get {
                return ResourceManager.GetString("Validation.InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không phải địa chỉ email hợp lệ..
        /// </summary>
        internal static string Validation_InvalidEmail {
            get {
                return ResourceManager.GetString("Validation.InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không đúng định dạng..
        /// </summary>
        internal static string Validation_InvalidFormat {
            get {
                return ResourceManager.GetString("Validation.InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không phải số điện thoại hợp lệ..
        /// </summary>
        internal static string Validation_InvalidPhone {
            get {
                return ResourceManager.GetString("Validation.InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tham chiếu đến bản ghi không tồn tại..
        /// </summary>
        internal static string Validation_InvalidReference {
            get {
                return ResourceManager.GetString("Validation.InvalidReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải nhỏ hơn hoặc bằng {1}..
        /// </summary>
        internal static string Validation_Max {
            get {
                return ResourceManager.GetString("Validation.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được vượt quá {1} ký tự..
        /// </summary>
        internal static string Validation_MaxLength {
            get {
                return ResourceManager.GetString("Validation.MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải lớn hơn hoặc bằng {1}..
        /// </summary>
        internal static string Validation_Min {
            get {
                return ResourceManager.GetString("Validation.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải có ít nhất {1} ký tự..
        /// </summary>
        internal static string Validation_MinLength {
            get {
                return ResourceManager.GetString("Validation.MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải là số nguyên..
        /// </summary>
        internal static string Validation_MustBeInteger {
            get {
                return ResourceManager.GetString("Validation.MustBeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải là số dương..
        /// </summary>
        internal static string Validation_MustBePositive {
            get {
                return ResourceManager.GetString("Validation.MustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải nằm trong khoảng từ {1} đến {2}..
        /// </summary>
        internal static string Validation_Range {
            get {
                return ResourceManager.GetString("Validation.Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải có độ dài từ {1} đến {2} ký tự..
        /// </summary>
        internal static string Validation_RangeLength {
            get {
                return ResourceManager.GetString("Validation.RangeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được để trống..
        /// </summary>
        internal static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu phải trước ngày kết thúc..
        /// </summary>
        internal static string Validation_StartDateGreaterThanEndDate {
            get {
                return ResourceManager.GetString("Validation.StartDateGreaterThanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực không hợp lệ hoặc đã hết hạn..
        /// </summary>
        internal static string Validation_TokkenInValid {
            get {
                return ResourceManager.GetString("Validation.TokkenInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã được phê duyệt thành công..
        /// </summary>
        internal static string Workflow_Approve_Success {
            get {
                return ResourceManager.GetString("Workflow.Approve.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã được hủy thành công..
        /// </summary>
        internal static string Workflow_Cancel_Success {
            get {
                return ResourceManager.GetString("Workflow.Cancel.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã được đóng thành công..
        /// </summary>
        internal static string Workflow_Close_Success {
            get {
                return ResourceManager.GetString("Workflow.Close.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể chuyển trạng thái từ {0} sang {1}..
        /// </summary>
        internal static string Workflow_InvalidTransition {
            get {
                return ResourceManager.GetString("Workflow.InvalidTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã được từ chối thành công..
        /// </summary>
        internal static string Workflow_Reject_Success {
            get {
                return ResourceManager.GetString("Workflow.Reject.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã được mở lại thành công..
        /// </summary>
        internal static string Workflow_Reopen_Success {
            get {
                return ResourceManager.GetString("Workflow.Reopen.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã được gửi phê duyệt thành công..
        /// </summary>
        internal static string Workflow_Submit_Success {
            get {
                return ResourceManager.GetString("Workflow.Submit.Success", resourceCulture);
            }
        }
    }
}
