//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysCategory_vi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysCategory_vi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Infrastructure.Resources.SysCategory.vi", typeof(SysCategory_vi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý danh mục nghiệp vụ.
        /// </summary>
        internal static string Module_BusinessCategory {
            get {
                return ResourceManager.GetString("Module.BusinessCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý tập tin.
        /// </summary>
        internal static string Module_Files {
            get {
                return ResourceManager.GetString("Module.Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý lập lịch công việc.
        /// </summary>
        internal static string Module_JobScheduler {
            get {
                return ResourceManager.GetString("Module.JobScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý chức danh.
        /// </summary>
        internal static string Module_JobTitle {
            get {
                return ResourceManager.GetString("Module.JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý menu.
        /// </summary>
        internal static string Module_Menu {
            get {
                return ResourceManager.GetString("Module.Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý phân cấp đơn vị.
        /// </summary>
        internal static string Module_OrganizationLevel {
            get {
                return ResourceManager.GetString("Module.OrganizationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý đơn vị.
        /// </summary>
        internal static string Module_OrganizationUnit {
            get {
                return ResourceManager.GetString("Module.OrganizationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý vai trò.
        /// </summary>
        internal static string Module_Roles {
            get {
                return ResourceManager.GetString("Module.Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý danh mục hệ thống.
        /// </summary>
        internal static string Module_SysCategories {
            get {
                return ResourceManager.GetString("Module.SysCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ người dùng.
        /// </summary>
        internal static string Module_UserProfile {
            get {
                return ResourceManager.GetString("Module.UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý vai trò của người dùng.
        /// </summary>
        internal static string Module_UserRole {
            get {
                return ResourceManager.GetString("Module.UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý người dùng.
        /// </summary>
        internal static string Module_Users {
            get {
                return ResourceManager.GetString("Module.Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        internal static string Permission_All {
            get {
                return ResourceManager.GetString("Permission.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt.
        /// </summary>
        internal static string Permission_Approve {
            get {
                return ResourceManager.GetString("Permission.Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới.
        /// </summary>
        internal static string Permission_Create {
            get {
                return ResourceManager.GetString("Permission.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string Permission_Delete {
            get {
                return ResourceManager.GetString("Permission.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        internal static string Permission_Edit {
            get {
                return ResourceManager.GetString("Permission.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        internal static string Permission_View {
            get {
                return ResourceManager.GetString("Permission.View", resourceCulture);
            }
        }
    }
}
