//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysCategory_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysCategory_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Infrastructure.Resources.SysCategory.en", typeof(SysCategory_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Category management.
        /// </summary>
        internal static string Module_BusinessCategory {
            get {
                return ResourceManager.GetString("Module.BusinessCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files management.
        /// </summary>
        internal static string Module_Files {
            get {
                return ResourceManager.GetString("Module.Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Scheduler management.
        /// </summary>
        internal static string Module_JobScheduler {
            get {
                return ResourceManager.GetString("Module.JobScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title management.
        /// </summary>
        internal static string Module_JobTitle {
            get {
                return ResourceManager.GetString("Module.JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu management.
        /// </summary>
        internal static string Module_Menu {
            get {
                return ResourceManager.GetString("Module.Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization level management.
        /// </summary>
        internal static string Module_OrganizationLevel {
            get {
                return ResourceManager.GetString("Module.OrganizationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization unit management.
        /// </summary>
        internal static string Module_OrganizationUnit {
            get {
                return ResourceManager.GetString("Module.OrganizationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles management.
        /// </summary>
        internal static string Module_Roles {
            get {
                return ResourceManager.GetString("Module.Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static system categories management.
        /// </summary>
        internal static string Module_SysCategories {
            get {
                return ResourceManager.GetString("Module.SysCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        internal static string Module_UserProfile {
            get {
                return ResourceManager.GetString("Module.UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Roles management.
        /// </summary>
        internal static string Module_UserRole {
            get {
                return ResourceManager.GetString("Module.UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users management.
        /// </summary>
        internal static string Module_Users {
            get {
                return ResourceManager.GetString("Module.Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Permission_All {
            get {
                return ResourceManager.GetString("Permission.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string Permission_Approve {
            get {
                return ResourceManager.GetString("Permission.Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Permission_Create {
            get {
                return ResourceManager.GetString("Permission.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Permission_Delete {
            get {
                return ResourceManager.GetString("Permission.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Permission_Edit {
            get {
                return ResourceManager.GetString("Permission.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string Permission_View {
            get {
                return ResourceManager.GetString("Permission.View", resourceCulture);
            }
        }
    }
}
