/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as appCategoriesIndexRouteImport } from './routes/(app)/categories/index'
import { Route as appSysUserIndexRouteImport } from './routes/(app)/sys/user/index'
import { Route as appSysRoleIndexRouteImport } from './routes/(app)/sys/role/index'
import { Route as appSysMenuIndexRouteImport } from './routes/(app)/sys/menu/index'
import { Route as appSysJobScheduleIndexRouteImport } from './routes/(app)/sys/job-schedule/index'
import { Route as appOrganizationJobTitleIndexRouteImport } from './routes/(app)/organization/job-title/index'
import { Route as appOrganizationDepartmentIndexRouteImport } from './routes/(app)/organization/department/index'
import { Route as appOrganizationDepartmentTypeIndexRouteImport } from './routes/(app)/organization/department-type/index'
import { Route as appSysUserIdRouteImport } from './routes/(app)/sys/user/$id'

const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appCategoriesIndexRoute = appCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => appRouteRoute,
} as any)
const appSysUserIndexRoute = appSysUserIndexRouteImport.update({
  id: '/sys/user/',
  path: '/sys/user/',
  getParentRoute: () => appRouteRoute,
} as any)
const appSysRoleIndexRoute = appSysRoleIndexRouteImport.update({
  id: '/sys/role/',
  path: '/sys/role/',
  getParentRoute: () => appRouteRoute,
} as any)
const appSysMenuIndexRoute = appSysMenuIndexRouteImport.update({
  id: '/sys/menu/',
  path: '/sys/menu/',
  getParentRoute: () => appRouteRoute,
} as any)
const appSysJobScheduleIndexRoute = appSysJobScheduleIndexRouteImport.update({
  id: '/sys/job-schedule/',
  path: '/sys/job-schedule/',
  getParentRoute: () => appRouteRoute,
} as any)
const appOrganizationJobTitleIndexRoute =
  appOrganizationJobTitleIndexRouteImport.update({
    id: '/organization/job-title/',
    path: '/organization/job-title/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appOrganizationDepartmentIndexRoute =
  appOrganizationDepartmentIndexRouteImport.update({
    id: '/organization/department/',
    path: '/organization/department/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appOrganizationDepartmentTypeIndexRoute =
  appOrganizationDepartmentTypeIndexRouteImport.update({
    id: '/organization/department-type/',
    path: '/organization/department-type/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSysUserIdRoute = appSysUserIdRouteImport.update({
  id: '/sys/user/$id',
  path: '/sys/user/$id',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/forbidden': typeof ForbiddenRoute
  '/': typeof appIndexRoute
  '/login/': typeof LoginIndexRoute
  '/test/': typeof TestIndexRoute
  '/categories/': typeof appCategoriesIndexRoute
  '/sys/user/$id': typeof appSysUserIdRoute
  '/organization/department-type/': typeof appOrganizationDepartmentTypeIndexRoute
  '/organization/department/': typeof appOrganizationDepartmentIndexRoute
  '/organization/job-title/': typeof appOrganizationJobTitleIndexRoute
  '/sys/job-schedule/': typeof appSysJobScheduleIndexRoute
  '/sys/menu/': typeof appSysMenuIndexRoute
  '/sys/role/': typeof appSysRoleIndexRoute
  '/sys/user/': typeof appSysUserIndexRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof ForbiddenRoute
  '/': typeof appIndexRoute
  '/login': typeof LoginIndexRoute
  '/test': typeof TestIndexRoute
  '/categories': typeof appCategoriesIndexRoute
  '/sys/user/$id': typeof appSysUserIdRoute
  '/organization/department-type': typeof appOrganizationDepartmentTypeIndexRoute
  '/organization/department': typeof appOrganizationDepartmentIndexRoute
  '/organization/job-title': typeof appOrganizationJobTitleIndexRoute
  '/sys/job-schedule': typeof appSysJobScheduleIndexRoute
  '/sys/menu': typeof appSysMenuIndexRoute
  '/sys/role': typeof appSysRoleIndexRoute
  '/sys/user': typeof appSysUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/(app)/': typeof appIndexRoute
  '/login/': typeof LoginIndexRoute
  '/test/': typeof TestIndexRoute
  '/(app)/categories/': typeof appCategoriesIndexRoute
  '/(app)/sys/user/$id': typeof appSysUserIdRoute
  '/(app)/organization/department-type/': typeof appOrganizationDepartmentTypeIndexRoute
  '/(app)/organization/department/': typeof appOrganizationDepartmentIndexRoute
  '/(app)/organization/job-title/': typeof appOrganizationJobTitleIndexRoute
  '/(app)/sys/job-schedule/': typeof appSysJobScheduleIndexRoute
  '/(app)/sys/menu/': typeof appSysMenuIndexRoute
  '/(app)/sys/role/': typeof appSysRoleIndexRoute
  '/(app)/sys/user/': typeof appSysUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forbidden'
    | '/'
    | '/login/'
    | '/test/'
    | '/categories/'
    | '/sys/user/$id'
    | '/organization/department-type/'
    | '/organization/department/'
    | '/organization/job-title/'
    | '/sys/job-schedule/'
    | '/sys/menu/'
    | '/sys/role/'
    | '/sys/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/'
    | '/login'
    | '/test'
    | '/categories'
    | '/sys/user/$id'
    | '/organization/department-type'
    | '/organization/department'
    | '/organization/job-title'
    | '/sys/job-schedule'
    | '/sys/menu'
    | '/sys/role'
    | '/sys/user'
  id:
    | '__root__'
    | '/(app)'
    | '/forbidden'
    | '/(app)/'
    | '/login/'
    | '/test/'
    | '/(app)/categories/'
    | '/(app)/sys/user/$id'
    | '/(app)/organization/department-type/'
    | '/(app)/organization/department/'
    | '/(app)/organization/job-title/'
    | '/(app)/sys/job-schedule/'
    | '/(app)/sys/menu/'
    | '/(app)/sys/role/'
    | '/(app)/sys/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginIndexRoute: typeof LoginIndexRoute
  TestIndexRoute: typeof TestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/categories/': {
      id: '/(app)/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof appCategoriesIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/sys/user/': {
      id: '/(app)/sys/user/'
      path: '/sys/user'
      fullPath: '/sys/user/'
      preLoaderRoute: typeof appSysUserIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/sys/role/': {
      id: '/(app)/sys/role/'
      path: '/sys/role'
      fullPath: '/sys/role/'
      preLoaderRoute: typeof appSysRoleIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/sys/menu/': {
      id: '/(app)/sys/menu/'
      path: '/sys/menu'
      fullPath: '/sys/menu/'
      preLoaderRoute: typeof appSysMenuIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/sys/job-schedule/': {
      id: '/(app)/sys/job-schedule/'
      path: '/sys/job-schedule'
      fullPath: '/sys/job-schedule/'
      preLoaderRoute: typeof appSysJobScheduleIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/organization/job-title/': {
      id: '/(app)/organization/job-title/'
      path: '/organization/job-title'
      fullPath: '/organization/job-title/'
      preLoaderRoute: typeof appOrganizationJobTitleIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/organization/department/': {
      id: '/(app)/organization/department/'
      path: '/organization/department'
      fullPath: '/organization/department/'
      preLoaderRoute: typeof appOrganizationDepartmentIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/organization/department-type/': {
      id: '/(app)/organization/department-type/'
      path: '/organization/department-type'
      fullPath: '/organization/department-type/'
      preLoaderRoute: typeof appOrganizationDepartmentTypeIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/sys/user/$id': {
      id: '/(app)/sys/user/$id'
      path: '/sys/user/$id'
      fullPath: '/sys/user/$id'
      preLoaderRoute: typeof appSysUserIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appCategoriesIndexRoute: typeof appCategoriesIndexRoute
  appSysUserIdRoute: typeof appSysUserIdRoute
  appOrganizationDepartmentTypeIndexRoute: typeof appOrganizationDepartmentTypeIndexRoute
  appOrganizationDepartmentIndexRoute: typeof appOrganizationDepartmentIndexRoute
  appOrganizationJobTitleIndexRoute: typeof appOrganizationJobTitleIndexRoute
  appSysJobScheduleIndexRoute: typeof appSysJobScheduleIndexRoute
  appSysMenuIndexRoute: typeof appSysMenuIndexRoute
  appSysRoleIndexRoute: typeof appSysRoleIndexRoute
  appSysUserIndexRoute: typeof appSysUserIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRoute: appIndexRoute,
  appCategoriesIndexRoute: appCategoriesIndexRoute,
  appSysUserIdRoute: appSysUserIdRoute,
  appOrganizationDepartmentTypeIndexRoute:
    appOrganizationDepartmentTypeIndexRoute,
  appOrganizationDepartmentIndexRoute: appOrganizationDepartmentIndexRoute,
  appOrganizationJobTitleIndexRoute: appOrganizationJobTitleIndexRoute,
  appSysJobScheduleIndexRoute: appSysJobScheduleIndexRoute,
  appSysMenuIndexRoute: appSysMenuIndexRoute,
  appSysRoleIndexRoute: appSysRoleIndexRoute,
  appSysUserIndexRoute: appSysUserIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginIndexRoute: LoginIndexRoute,
  TestIndexRoute: TestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
